name: CI
on:
  push:
  pull_request:
jobs:
  build:
    name: WASM Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.45
          actions-cache-folder: emsdk-cache
      - name: Build RGBDS
        run: ./build-rgbds.sh
        shell: bash
      - name: Build binjgb
        run: ./build-binjgb.sh
        shell: bash
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install node dependencies
        run: npm ci
      - name: Build with Vite
        run: npm run build
      - name: Deploy to GitHub Pages
        # Do not run this unless *pushing* to `master`.
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./www
